export const FETCH_WKFL_BY_ORG_START = 'FETCH_WKFL_BY_ORG_START';
export const FETCH_WKFL_BY_ORG_SUCCESS = 'FETCH_WKFL_BY_ORG_SUCCESS';
export const FETCH_WKFL_BY_ORG_FAIL = 'FETCH_WKFL_BY_ORG_FAIL';


export const FETCH_ST_BY_WKFL_START = 'FETCH_ST_BY_WKFL_START';
export const FETCH_ST_BY_WKFL_SUCCESS = 'FETCH_ST_BY_WKFL_SUCCESS';
export const FETCH_ST_BY_WKFL_FAIL = 'FETCH_ST_BY_WKFL_FAIL';

export const CREATE_TRANSACTION_START = 'CREATE_TRANSACTION_START';
export const CREATE_TRANSACTION_SUCCESS = 'CREATE_TRANSACTION_SUCCESS';
export const CREATE_TRANSACTION_FAIL = 'CREATE_TRANSACTION_FAIL';
