export const FETCH_ALL_PERMISSIONS_START = 'FETCH_ALL_PERMISSIONS_START';
export const FETCH_ALL_PERMISSIONS_SUCCESS = 'FETCH_ALL_PERMISSIONS_SUCCESS';
export const FETCH_ALL_PERMISSIONS_FAIL = 'FETCH_ALL_PERMISSIONS_FAIL';

