export const FETCH_FARMER_APPRV_START ='FETCH_FARMER_APPRV_START';
export const FETCH_FARMER_APPRV_SUCCESS ='FETCH_FARMER_APPRV_SUCCESS';
export const FETCH_FARMER_APPRV_FAIL ='FETCH_FARMER_APPRV_FAIL';


export const FETCH_ONE_FARMER_APPRV_START ='FETCH_ONE_FARMER_APPRV_START';
export const FETCH_ONE_FARMER_APPRV_SUCCESS ='FETCH_ONE_FARMER_APPRV_SUCCESS';
export const FETCH_ONE_FARMER_APPRV_FAIL ='FETCH_ONE_FARMER_APPRV_FAIL';

export const FARMER_APPRV_START ='FARMER_APPRV_START';
export const FARMER_APPRV_SUCCESS ='FARMER_APPRV_SUCCESS';
export const FARMER_APPRV_FAIL ='FARMER_APPRV_FAIL';



