export const CREATE_PLOT_START ='CREATE_PLOT_START';
export const CREATE_PLOT_SUCCESS ='CREATE_PLOT_SUCCESS';
export const CREATE_PLOT_FAIL ='CREATE_PLOT_FAIL';


export const FETCH_PLOT_APPV_START ='FETCH_PLOT_APPV_START';
export const FETCH_PLOT_APPV_SUCCESS ='FETCH_PLOT_APPV_SUCCESS';
export const FETCH_PLOT_APPV_FAIL ='GET_PLOT_APPV_FAIL';


