export const CREATE_WORKFLOW_START = 'CREATE_WORKFLOW_START';
export const CREATE_WORKFLOW_SUCCESS = 'CREATE_WORKFLOW_SUCCESS';
export const CREATE_WORKFLOW_FAIL = 'CREATE_WORKFLOW_FAIL';


export const CREATE_GET_WORKFLOW_START = 'CREATE_GET_WORKFLOW_START';
export const CREATE_GET_WORKFLOW_SUCCESS = 'CREATE_GET_WORKFLOW_SUCCESS';
export const CREATE_GET_WORKFLOW_FAIL = 'CREATE_GET_WORKFLOW_FAIL';


export const CREATE_STATES_START = 'CREATE_STATES_START';
export const CREATE_STATES_SUCCESS = 'CREATE_STATES_SUCCESS';
export const CREATE_STATES_FAIL = 'CREATE_STATES_FAIL';

