export const FETCH_ORGANIZATIONS_START = 'FETCH_ORGANIZATIONS_START';
export const FETCH_ORGANIZATIONS_SUCCESS = 'FETCH_ORGANIZATIONS_SUCCESS';
export const FETCH_ORGANIZATIONS_FAILED = 'FETCH_ORGANIZATIONS_FAILED';

export const FETCH_ORGnROLES_START = 'FETCH_ORGnROLES_START';
export const FETCH_ORGnROLES_SUCCESS = 'FETCH_ORGnROLES_SUCCESS';
export const FETCH_ORGnROLES_FAILED = 'FETCH_ORGANIZATIONS_FAILED';
