export const CREATE_PLOT_START ='CREATE_PLOT_START';
export const CREATE_PLOT_SUCCESS ='CREATE_PLOT_SUCCESS';
export const CREATE_PLOT_FAIL ='CREATE_PLOT_FAIL';


export const FETCH_PLOT_APPV_START ='FETCH_PLOT_APPV_START';
export const FETCH_PLOT_APPV_SUCCESS ='FETCH_PLOT_APPV_SUCCESS';
export const FETCH_PLOT_APPV_FAIL ='GET_PLOT_APPV_FAIL';


export const FETCH_ONE_PLOT_APPV_START ='FETCH_ONE_PLOT_APPV_START';
export const FETCH_ONE_PLOT_APPV_SUCCESS ='FETCH_ONE_PLOT_APPV_SUCCESS';
export const FETCH_ONE_PLOT_APPV_FAIL ='FETCH_ONE_PLOT_APPV_FAIL';

export const APPV_PLOT_START ='APPV_PLOT_START';
export const APPV_PLOT_SUCCESS ='APPV_PLOT_SUCCESS';
export const APPV_PLOT_FAIL ='APPV_PLOT_FAIL';



